Added the css files to match the card pattern
razvanpan/single-patient-view pull request #29
Opened 2020-10-19 12:41 UTC by AlexandruLung

2020-10-20 12:28 UTC, imartinas approved these changes
Looks good

2020-10-21 10:21 UTC, andreeacojocaru731 requested changes

2020-10-21 10:21 UTC, andreeacojocaru731 commented on patient-view-fe/src/components/chief-complaint/chief-complaint.component.css
> +  background-color: #e5eef9;
Please set the colors inside of the application and don't use div>div>div

2020-10-26 07:49 UTC, andreeacojocaru731 approved these changes

2020-10-26 07:56 UTC, merged