-added backend functionality for physical examination
razvanpan/single-patient-view pull request #5
Opened 2020-09-28 12:16 UTC by MezeiSebastian

2020-10-02 09:55 UTC, sweetphilosophy requested changes
Please let me know your thoughts! Make sure to format the code.
Also, is the project working as expected for you?

2020-10-02 09:55 UTC, sweetphilosophy commented on patient-view-be/src/main/java/spvproject/patientviewbe/repository/PhysicalExaminationRepository.java
> +public interface PhysicalExaminationRepository extends JpaRepository<PhysicalExamination,Long> {
Shouldn't this extend `CrudRepository?`

2020-10-02 11:16 UTC, sweetphilosophy approved these changes
Looks good to me, thanks for following up the comments

2020-10-05 10:09 UTC, andreeacojocaru731 approved these changes

2020-10-05 10:10 UTC, merged