created PatientBannerModel, PatientBannerController, endpoint and also tested in postman
razvanpan/single-patient-view pull request #6
Opened 2020-09-29 09:34 UTC by lorenaanghel

Everything works properly.

2020-09-30 09:07 UTC, andreeacojocaru731 requested changes
Please remove the bin folder, it should not be committed.

2020-10-02 09:52 UTC, sweetphilosophy requested changes
Let me know your thoughts!
Also, please make sure to remove the `/bin/` folder as Andreea mentioned. I think you didn't merged master into your branch before working? I could be wrong!
In any case, only the source files should be committed

2020-10-02 09:52 UTC, sweetphilosophy commented on patient-view-be/src/main/java/spvproject/patientviewbe/model/PatientBannerModel.java
> +public class PatientBannerModel {
This can be simply called `PatientBanner`

2020-10-02 11:18 UTC, sweetphilosophy commented on patient-view-be/src/main/java/spvproject/patientviewbe/controller/PatientBannerController.java
> +@RequestMapping("GET/patient-banner")
You can remove the `GET` from here.

2020-10-05 08:37 UTC, sweetphilosophy approved these changes
Looks goo to me. Thanks for following up the comments

2020-10-13 13:00 UTC, andreeacojocaru731 approved these changes

2020-10-13 13:01 UTC, merged